import Head from "next/head";
import Image from "next/image";

const Home = ({ data }: { data: any[] }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing <code>pages/index.tsx</code>
        </p>

        <div>
          {data?.map((item, index) => {
            return (
              <a href="https://nextjs.org/docs" key={index}>
                <h2>{item.name}</h2>
                <p>{item.email}</p>
              </a>
            );
          })}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
              layout="fixed"
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
